### ISSUE TITLE
Reverting from block to state-by-state removal

### ISSUE THREAD

**Issue by kannandeepti** [tomswinburne/PyGT#3]
Docs say that GT code should revert to state-by-state removal if the matrix inversion fails, but that doesn't seem to happen when computing MFPT matrices using code defaults. See attached: top figure is computation I did for the manuscript, bottom figure is using code defaults (block=10). I've changed the defaults to block=1 to ensure numerics are stable for the notebook computations, but we should fix the automated reversion to state-by-state.

![block_size_numerical_stability](https://user-images.githubusercontent.com/35346947/87651320-b692e480-c707-11ea-8e8a-8fcb60d2aa75.png)

**Comment by tomswinburne** [comment]
Closing this as it passes my tests
