### ISSUE TITLE
documentation in coarse_graining_example

### ISSUE THREAD

**Issue by tomswinburne** [tomswinburne/PyGT#4]
If we want to include examples/coarse_graining_example.ipynb we need to have a little bit of explanation text  in the notebook

**Comment by kannandeepti** [comment]
Just saw your changes to the notebook. I added some explanation of the plots to the notebook. Also, how did you suppress the error messages from HS/KKRA schemes?

**Comment by tomswinburne** [comment]
I just went to higher temperatures I think for the notebook example. If the
method fails we will get error messages, as one might hope...
--
Thomas D Swinburne
Chargé de recherche, CNRS
CINaM, Campus de Luminy, Marseille
email: swinburne@cinam.univ-mrs.fr
tel: +33 6 62 90 28 87
web: https://tomswinburne.github.io
